app:
  datasource:
    url: jdbc:postgresql://localhost:5455/test_db
    username: test
    password: test
    configuration:


spring:
  application:
    name: market-bot
  main:
    web-application-type: none
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: marketbot
        connection:
          pool_size: 30

market-bot:
  #finnhub-api-key: ${FINNHUB_API_KEY:xxxx}
  #twelve-data-api-key: ${TWELVE_API_KEY:$4k24k24k23kl4}
  telegram-bot-token: ${TELEGRAM_BOT_TOKEN:xxx}
  telegram-chat-id: ${TELEGRAM_CHAT_ID:11111111}

  watchlist:

    # =====================================================
    # EUROPE - Use exchange suffixes for Yahoo
    # =====================================================
    ABB.ST: ABB

  # Send a DOWN alert only when the current daily change is less than or equal to this value.
  # Example: -0.4 means the share must be down at least 0.4% for the day.
  drop-alert-percent: -0.4

  # Send an UP alert only when the current daily change is greater than or equal to this value.
  # Example: 0.4 means the share must be up at least 0.4% for the day.
  rise-alert-percent: 0.4

  # Delay between market scans in milliseconds.
  # Example: 30000 means the app checks the watchlist every 30 seconds.
  poll-interval-ms: 10000

  # Minimum accumulated movement required before an alert can be sent.
  # Example: 0.8 means the rolling price movement must be at least 0.8% up or down.
  maximal-delta-price: 0.8
