spring:
  application:
    name: market-bot
  main:
    web-application-type: none
  docker:
    compose:
      enabled: false

market-bot:
  finnhub-api-key: ${FINNHUB_API_KEY:xxxx}
  telegram-bot-token: ${TELEGRAM_BOT_TOKEN:xxx}
  telegram-chat-id: ${TELEGRAM_CHAT_ID:11111111}
  twelve-data-api-key: ${TWELVE_API_KEY:$4k24k24k23kl4}

  watchlist:
    # =========================
    # USA - Semiconductors / AI / Tech
    # =========================
    AAPL: Apple
    #ADPT: Adaptive Biotechnologies
    AMAT: Applied Materials
    AMD: Advanced Micro Devices
    ARM: Arm Holdings
    AVGO: Broadcom
    #BLK: BlackRock
    #GOOGL: Google
    #IBM: IBM
    INTC: Intel
    LITE: Lumentum Holdings
    MCHP: Microchip Technology
    #MSFT: Microsoft
    MU: Micron Technology
    NVDA: NVIDIA
    NVTS: Navitas Semiconductor
    ORCL: Oracle
    OUST: Ouster
    #PLTR: Palantir Technologies
    QCOM: Qualcomm
    RMBS: Rambus
    IONQ: IonQ Quantum Computers
    QUBT: Quantum Computing Inc
    #TSM: Taiwan Semiconductor Manufacturing Company
    RKLB: Rocket Lab

    # =========================
    # USA - AI / Robotics / Biotech
    # =========================
    #GLSI: Greenwich LifeSciences
    #IBRX: ImmunityBio
    LIDR: AEye
    #VTYX: Ventyx Biosciences

    # =========================
    # USA - Mining / Lithium / Metals
    # =========================
    #AG: First Majestic Silver
    CENX: Century Aluminum
    EXK: Endeavour Silver
    LAC: Lithium Americas
    #MP: MP Materials
    #NEM: Newmont
    #PAAS: Pan American Silver
    SCCO: Southern Copper
    SGML: Sigma Lithium
    SLI: Standard Lithium
    #SVM: Silvercorp Metals

    # =========================
    # USA - Energy / Utilities
    # =========================
    CVX: Chevron
    #NRGV: Energy Vault
    #SHEL: Shell
    #VST: Vistra
    #XOM: ExxonMobil

    # =========================
    # USA - Industrial / Infrastructure
    # =========================
    #AMTM: Amentum Holdings
    ATRO: Astronics
    #DE: Deere & Company
    #FTAI: FTAI Aviation
    #NOV: NOV
    #NVT: nVent Electric
    #VICR: Vicor

    # =========================
    # USA - Automotive / EV
    # =========================
    #GM: General Motors
    #TSLA: Tesla

    # =========================
    # USA - Finance
    # =========================
    SEI: SEI Investments

    # =========================
    # USA - Telecom / Networking
    # =========================
    NOK: Nokia

    # =========================
    # USA - Consumer / Food
    # =========================
    #BYND: Beyond Meat
    CHEF: The Chefs' Warehouse

    # =========================
    # Healthcare / Insurance
    # =========================
    UNH: UnitedHealth Group

    # =====================================================
    # EUROPE - Use exchange suffixes for Yahoo
    # =====================================================
    ABB.ST: ABB
    ABBN.SW: ABJ ABB
    ROG.SW: Roche Holding AG
    AIR.PA: Airbus
    BMW.DE: BMW
    ASML: ASML Holding
    ASML.AS: ASML Holding
    BAYN.DE: Bayer
    ENR.DE: Siemens Energy AG
    SIE.DE: Siemens AG
    NVS: Novartis AG US
    NOVN.SW: Novartis Swiss
    #RHM.DE: Rheinmetall
    STM: STMicroelectronics

  drop-alert-percent: -0.4
  rise-alert-percent: 0.4
  poll-interval-ms: 30000
  maximal-delta-price: 0.8
